force-app/main/default/objects/Rollup_Config__mdt/Rollup_Config__mdt.object-meta.xml
<CustomObject>
    <description>Generic Roll-Up Configuration</description>
    <label>Rollup Config</label>
    <pluralLabel>Rollup Configs</pluralLabel>
</CustomObject>

force-app/main/default/objects/Rollup_Config__mdt/fields/Aggregate_Function__c.field-meta.xml
<CustomField>
    <fullName>Aggregate_Function__c</fullName>
    <label>Aggregate Function</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SUM</fullName>
                <default>true</default>
                <label>SUM</label>
            </value>
            <value>
                <fullName>AVG</fullName>
            </value>
            <value>
                <fullName>MIN</fullName>
            </value>
            <value>
                <fullName>MAX</fullName>
            </value>
            <value>
                <fullName>COUNT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Rollup_Config__mdt/fields/Child_Field__c.field-meta.xml
<CustomField>
    <fullName>Child_Field__c</fullName>
    <label>Child Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rollup_Config__mdt/fields/Child_Object__c.field-meta.xml
<CustomField>
    <fullName>Child_Object__c</fullName>
    <label>Child Object</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/rollUpEngineTask/RollupEngineConstants.cls
public with sharing class RollupEngineConstants {

    public static final String SUM_FUNCTION = 'SUM';
    public static final String AVG_FUNCTION = 'AVG';
    public static final String MIN_FUNCTION = 'MIN';
    public static final String MAX_FUNCTION = 'MAX';
    public static final String COUNT_FUNCTION = 'COUNT';

    public static final String AGGREGATE_ALIAS = 'aggregateValue';

    public static final String ROLLUP_METADATA = 'Rollup_Config__mdt';

    public static final String PARENT_OBJECT_API = 'Parent_Object__c';
    public static final String PARENT_OBJECT_FIELD = 'Parent_Field__c';
    public static final String CHILD_OBJECT_API = 'Child_Object__c';
    public static final String CHILD_OBJECT_FIELD = 'Child_Field__c';
    public static final String RELATIONSHIP_FIELD = 'Relationship_Field__c';
    public static final String AGGREGATE_FUNCTION = 'Aggregate_Function__c';
    public static final String ACTIVE_FIELD = 'Active__c';
}