force-app/main/default/objects/Rollup_Config__mdt/Rollup_Config__mdt.object-meta.xml
<CustomObject>
    <description>Generic Roll-Up Configuration</description>
    <label>Rollup Config</label>
    <pluralLabel>Rollup Configs</pluralLabel>
</CustomObject>

force-app/main/default/objects/Rollup_Config__mdt/fields/Aggregate_Function__c.field-meta.xml
<CustomField>
    <fullName>Aggregate_Function__c</fullName>
    <label>Aggregate Function</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SUM</fullName>
                <default>true</default>
                <label>SUM</label>
            </value>
            <value>
                <fullName>AVG</fullName>
            </value>
            <value>
                <fullName>MIN</fullName>
            </value>
            <value>
                <fullName>MAX</fullName>
            </value>
            <value>
                <fullName>COUNT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Rollup_Config__mdt/fields/Child_Field__c.field-meta.xml
<CustomField>
    <fullName>Child_Field__c</fullName>
    <label>Child Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rollup_Config__mdt/fields/Child_Object__c.field-meta.xml
<CustomField>
    <fullName>Child_Object__c</fullName>
    <label>Child Object</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/rollUpEngineTask/RollupEngineMetadataService.cls
public with sharing class RollupEngineMetadataService {

    // reuturns all active roll-up configurations for the specified child object

    public static List<Rollup_Config__mdt> getRollupConfigurations(String childObjectApiName) {

        if (String.isBlank(childObjectApiName)) {
            return new List<Rollup_Config__mdt>();
        }

        return [
            SELECT Parent_Object__c,
                   Parent_Field__c,
                   Child_Object__c,
                   Child_Field__c,
                   Relationship_Field__c,
                   Aggregate_Function__c,
                   Active__c
            FROM Rollup_Config__mdt
            WHERE Child_Object__c = :childObjectApiName
            AND Active__c = true
        ];
    }
}